version: '3'
services:

  blablacar.front.googlemaps:
    build: ./reactgooglemaps
    env_file:
      - .env
    ports:
      - '80:3000'
    volumes:
      - './reactgooglemaps/src:/app/src'
    networks:
      - blablacar

networks:
  blablacar:
    driver: bridge